Cl abap datfm
open-abap/open-abap-core pull request #661
Opened 2023-05-05 21:39 UTC by dominikpanzer

Hi,

I wrote a quite naive implementation of the method `CONV_DATE_EXT_TO_INT`, because _really_ correct date validation is painful.  It's the only method of this class that I personally need. The conversion is only possible for dates in format DD.MM.YYYY and is guarded by a regex. 

Greetings,
Dominik

2023-05-06 04:06 UTC, larshp commented on src/date_time/cl_abap_datfm.clas.abap
> -    CLASS-METHODS get_date_format_des
keep this method definition in the source code

2023-05-06 04:07 UTC, larshp commented
naive: no problem, one step at a time. Its good to merge after adding the old method definition back in

2023-05-06 15:32 UTC, larshp requested changes
see above

2023-05-06 19:46 UTC, dominikpanzer commented
done :-)

2023-05-07 05:16 UTC, larshp approved these changes

2023-05-07 05:16 UTC, larshp commented
thanks 👍

2023-05-07 05:17 UTC, merged