`/ui2/cl_json`: add inherit functionality
open-abap/open-abap-core pull request #831
Opened 2024-01-19 13:15 UTC by oblomov-dev

open-abap is not working when a class inherits /ui2/json:
https://github.com/abap2UI5/abap2UI5/actions/runs/7583976799/job/20656717865?pr=793

added:
* constructor
* is_compressable
* serialize_int (and added the code of the serialize method)
* added attributes used in the constructor

next step / issue: 
* adjusting serialize_int with respecting the value mv_extended.

I have no idea if this inheriting concept is easily implementable in open-abap? before i start making changes here without knowing how this all specifically works, maybe its better you comment on this first.

2024-01-19 13:23 UTC, larshp commented
inheritance should work in open-abap, so all good

2024-01-19 13:34 UTC, larshp commented
@oblomov-dev if you dont have vscode installed, you can try https://github.com/github/dev, it might be easier

2024-01-19 13:38 UTC, oblomov-dev commented
yes github codespaces (i think it is the same) is my second home after eclipse :) i will check it!

2024-01-20 01:17 UTC, oblomov-dev commented
ok, fixed all the linter issues now, all tests are green.

i skipped implementing the call of the "is_compressable" method, means from my understanding: you can inherit /ui2/cl_json now but when you create a unit test based on a change implemented in is_compressable, open-abap will give a different result than the normal abap stack but maybe for the first step, this is enough.

2024-01-20 07:50 UTC, larshp requested changes
see comments

2024-01-20 07:50 UTC, larshp commented on src/json/#ui2#cl_json.clas.abap
> +    METHODS is_compressable
move this method to PROTECTED SECTION ?

2024-01-20 07:50 UTC, larshp commented on src/json/#ui2#cl_json.clas.abap
> +    DATA mv_extended TYPE abap_bool.
also protected section?

2024-01-20 07:50 UTC, larshp commented on src/json/#ui2#cl_json.clas.abap
> +*            ts_as_iso8601 = mv_ts_as_iso8601
```suggestion
```

2024-01-20 07:50 UTC, larshp commented on src/json/#ui2#cl_json.clas.abap
> +*           ts_as_iso8601 = ts_as_iso8601 ).
```suggestion
```

2024-01-20 07:50 UTC, larshp commented on src/json/#ui2#cl_json.clas.abap
> +*          ts_as_iso8601 = ts_as_iso8601 ).
```suggestion
```

2024-01-20 08:21 UTC, oblomov-dev commented
see this review and comment function for the first time, nice! code is adjusted.

2024-01-20 08:46 UTC, larshp approved these changes
thanks 👍

2024-01-20 08:47 UTC, larshp commented
if the compress inheritance and stuff doesnt work, suggest as next step adding a unit test for it in https://github.com/oblomov-dev/open-abap-core/blob/main/src/json/%23ui2%23cl_json.clas.testclasses.abap

2024-01-20 08:47 UTC, merged

2024-01-20 09:05 UTC, oblomov-dev commented
@larshp 
ok, would there also be the chance to debug the code? can i for example rename it to zui2_cl_json, copy it to an abap stack and run the unit tests or what is the recommended way?

2024-01-20 09:09 UTC, larshp commented
that might work

typically I dont debug much, when there is a simple unit test for it its easy to find the bug

standalone debuggin also works a bit,
![image](https://github.com/open-abap/open-abap-core/assets/5888506/f53bf067-0f52-4dfb-9cfe-05846659d50e)

2024-01-20 09:15 UTC, oblomov-dev commented
ah ok interesting, i will try it out :)